package algonquin.cst2335.finalapplication.WeatherStack.database;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * This class represents the  weatherstack object and its corresponding attributes.
 */

@Entity
public class WeatherStack {

    //Autogenerated ID for database purposes.
    @PrimaryKey (autoGenerate = true)
    @ColumnInfo(name="id")
    public int id;

    @ColumnInfo(name="city_name")
    String cityName;

    @ColumnInfo(name="country_name")
    String countryName;

    @ColumnInfo(name="temperature")
    int temperature;

    @ColumnInfo(name="date_time")
    String dateTime;

    @ColumnInfo(name="thumbnail_icon")
    String weatherThumnailIcon;

    @ColumnInfo(name="observed_time")
    String observedTime;

    @ColumnInfo(name="precipitation")
    int precipitation;

    @ColumnInfo(name="humidity")
    int humidity;

    @ColumnInfo(name="uv_index")
    int uvIndex;

    @ColumnInfo(name="pressure")
    int pressure;

    @ColumnInfo(name="visibility")
    int visibility;

    @ColumnInfo(name="wind_speed")
    int windSpeed;

    @ColumnInfo(name="wind_degree")
    int windDegree;

    @ColumnInfo(name="wind_direction")
    String windDirection;

    @ColumnInfo(name="cloud_cover")
    int cloudCover;

    @ColumnInfo(name="feel_like")
    int feelLike;

    @ColumnInfo(name="weather_desc")
    String weatherDesc;


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    public int getTemperature() {
        return temperature;
    }

    public void setTemperature(int temperature) {
        this.temperature = temperature;
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public String getWeatherThumnailIcon() {
        return weatherThumnailIcon;
    }

    public void setWeatherThumnailIcon(String weatherThumnailIcon) {
        this.weatherThumnailIcon = weatherThumnailIcon;
    }

    public String getObservedTime() {
        return observedTime;
    }

    public void setObservedTime(String observedTime) {
        this.observedTime = observedTime;
    }

    public int getPrecipitation() {
        return precipitation;
    }

    public void setPrecipitation(int precipitation) {
        this.precipitation = precipitation;
    }

    public int getHumidity() {
        return humidity;
    }

    public void setHumidity(int humidity) {
        this.humidity = humidity;
    }

    public int getUvIndex() {
        return uvIndex;
    }

    public void setUvIndex(int uvIndex) {
        this.uvIndex = uvIndex;
    }

    public int getPressure() {
        return pressure;
    }

    public void setPressure(int pressure) {
        this.pressure = pressure;
    }

    public int getVisibility() {
        return visibility;
    }

    public void setVisibility(int visibility) {
        this.visibility = visibility;
    }

    public int getWindSpeed() {
        return windSpeed;
    }

    public void setWindSpeed(int windSpeed) {
        this.windSpeed = windSpeed;
    }

    public int getWindDegree() {
        return windDegree;
    }

    public void setWindDegree(int windDegree) {
        this.windDegree = windDegree;
    }

    public String getWindDirection() {
        return windDirection;
    }

    public void setWindDirection(String windDirection) {
        this.windDirection = windDirection;
    }

    public int getCloudCover() {
        return cloudCover;
    }

    public void setCloudCover(int cloudCover) {
        this.cloudCover = cloudCover;
    }

    public int getFeelLike() {
        return feelLike;
    }

    public void setFeelLike(int feelLike) {
        this.feelLike = feelLike;
    }

    public String getWeatherDesc() {
        return weatherDesc;
    }

    public void setWeatherDesc(String weatherDesc) {
        this.weatherDesc = weatherDesc;
    }
}


